name: rmutt_social
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase packages
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  
  # Authentication
  google_sign_in: ^6.2.1
  
  # Media handling
  image_picker: ^1.1.2
  video_player: ^2.9.1
  
  # UI components
  cached_network_image: ^3.4.1
  
  # State management and utilities
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  
  # Notifications
  flutter_local_notifications: ^17.2.3
  firebase_messaging: ^15.1.3
  
  # HTTP requests
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
